create table public.accounts (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  name text not null check (length(btrim(name)) between 1 and 200),
  legal_name text,
  industry text,
  company_size text,
  region text,
  website text,
  owner_member_id uuid,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id)
);

create table public.contacts (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  account_id uuid,
  owner_member_id uuid,
  status public.contact_status not null default 'provisional',
  full_name text not null check (length(btrim(full_name)) between 1 and 160),
  phone text,
  phone_verified_at timestamptz,
  email text,
  email_verified_at timestamptz,
  wechat text,
  identity_pending boolean not null default false,
  merged_into_contact_id uuid,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, account_id) references public.accounts(organization_id, id) on delete set null,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, merged_into_contact_id) references public.contacts(organization_id, id) on delete set null,
  unique (organization_id, id),
  check ((status = 'merged' and merged_into_contact_id is not null) or status <> 'merged')
);

create table public.leads (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  public_id text not null default ('LD-' || upper(substr(replace(extensions.gen_random_uuid()::text, '-', ''), 1, 12))),
  contact_id uuid not null,
  account_id uuid,
  owner_member_id uuid,
  status public.lead_status not null default 'new',
  source text not null,
  source_connection_id uuid,
  need text,
  budget_amount numeric(16,2) check (budget_amount is null or budget_amount >= 0),
  budget_currency text default 'CNY' check (budget_currency is null or budget_currency ~ '^[A-Z]{3}$'),
  urgency text,
  notes text,
  consent jsonb not null default '{}'::jsonb,
  tracking jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  acknowledged_at timestamptz,
  accepted_at timestamptz,
  last_contacted_at timestamptz,
  converted_at timestamptz,
  invalid_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, account_id) references public.accounts(organization_id, id) on delete set null,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  unique (organization_id, public_id)
);

create table public.pipeline_stages (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  name text not null check (length(btrim(name)) between 1 and 80),
  stage_key text not null check (stage_key ~ '^[a-z][a-z0-9_]{1,40}$'),
  position integer not null check (position >= 0),
  is_default boolean not null default false,
  is_closed boolean not null default false,
  is_won boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  unique (organization_id, id),
  unique (organization_id, stage_key),
  unique (organization_id, position),
  check (not is_won or is_closed)
);

create table public.opportunities (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid not null,
  account_id uuid,
  lead_id uuid not null,
  owner_member_id uuid,
  pipeline_stage_id uuid not null,
  status public.opportunity_status not null default 'open',
  is_primary boolean not null default true,
  title text not null check (length(btrim(title)) between 1 and 200),
  amount numeric(16,2) check (amount is null or amount >= 0),
  currency text not null default 'CNY' check (currency ~ '^[A-Z]{3}$'),
  expected_close_date date,
  won_at timestamptz,
  lost_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, account_id) references public.accounts(organization_id, id) on delete set null,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, pipeline_stage_id) references public.pipeline_stages(organization_id, id) on delete restrict,
  unique (organization_id, id),
  check ((status = 'won' and won_at is not null) or status <> 'won')
);
