create table public.activities (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid,
  lead_id uuid,
  opportunity_id uuid,
  owner_member_id uuid,
  actor_member_id uuid,
  activity_type text not null check (activity_type ~ '^[a-z][a-z0-9_]{1,60}$'),
  title text not null check (length(btrim(title)) between 1 and 200),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, opportunity_id) references public.opportunities(organization_id, id) on delete restrict,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, actor_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id)
);

create table public.follow_up_tasks (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid,
  lead_id uuid,
  opportunity_id uuid,
  assignee_member_id uuid,
  created_by_member_id uuid,
  status public.task_status not null default 'open',
  title text not null check (length(btrim(title)) between 1 and 200),
  notes text,
  due_at timestamptz not null,
  snoozed_until timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  outcome public.message_outcome,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, opportunity_id) references public.opportunities(organization_id, id) on delete restrict,
  foreign key (organization_id, assignee_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, created_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  check (num_nonnulls(contact_id, lead_id, opportunity_id) >= 1),
  check ((status = 'completed' and completed_at is not null) or status <> 'completed'),
  check ((status = 'snoozed' and snoozed_until is not null) or status <> 'snoozed')
);
