create table public.organization_scoring_profiles (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  name text not null,
  profile_version integer not null check (profile_version > 0),
  status text not null check (status in ('draft', 'active', 'retired')),
  currency text not null default 'CNY' check (currency ~ '^[A-Z]{3}$'),
  pricing_model text,
  minimum_viable_budget numeric(16,2) check (minimum_viable_budget is null or minimum_viable_budget >= 0),
  target_budget_min numeric(16,2) check (target_budget_min is null or target_budget_min >= 0),
  target_budget_max numeric(16,2) check (target_budget_max is null or target_budget_max >= 0),
  target_industries text[] not null default '{}',
  target_company_sizes text[] not null default '{}',
  target_regions text[] not null default '{}',
  target_use_cases text[] not null default '{}',
  target_buyer_roles text[] not null default '{}',
  positive_signals text[] not null default '{}',
  disqualifying_signals text[] not null default '{}',
  effective_from timestamptz not null default now(),
  created_by_member_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, created_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  unique (organization_id, profile_version),
  check (target_budget_max is null or target_budget_min is null or target_budget_max >= target_budget_min)
);

create table public.lead_scores (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  lead_id uuid not null,
  scoring_profile_id uuid not null,
  scoring_rule_version text not null default 'standard_v1',
  prompt_version text not null,
  status public.score_status not null,
  total_score numeric(5,2) check (total_score between 0 and 100),
  raw_known_score numeric(5,2) not null check (raw_known_score between 0 and 100),
  known_weight numeric(5,2) not null check (known_weight between 0 and 100),
  normalized_score numeric(5,2) check (normalized_score between 0 and 100),
  coverage numeric(5,4) not null check (coverage between 0 and 1),
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  priority_level public.priority_level,
  dimension_scores jsonb not null,
  score_reasons jsonb not null default '{}'::jsonb,
  missing_information jsonb not null default '[]'::jsonb,
  recommended_next_action text,
  ai_provider text not null,
  ai_model text not null,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  scored_by text not null default 'automation',
  scored_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, scoring_profile_id) references public.organization_scoring_profiles(organization_id, id) on delete restrict,
  unique (organization_id, id),
  check ((known_weight = 0 and normalized_score is null) or known_weight > 0),
  check (jsonb_typeof(dimension_scores) = 'object'),
  check (jsonb_typeof(missing_information) = 'array')
);

create table public.score_history (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  lead_id uuid not null,
  lead_score_id uuid not null,
  snapshot jsonb not null,
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_score_id) references public.lead_scores(organization_id, id) on delete restrict,
  unique (organization_id, id)
);
