create table public.channel_connections (
  id uuid primary key default extensions.gen_random_uuid(),
  public_id text not null default encode(extensions.gen_random_bytes(18), 'hex'),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  provider public.provider_code not null,
  name text not null,
  status public.connection_status not null default 'draft',
  secret_ref text,
  public_config jsonb not null default '{}'::jsonb,
  capabilities jsonb not null default '{}'::jsonb,
  validated_at timestamptz,
  last_error_code text,
  created_by_member_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, created_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  unique (public_id),
  unique (organization_id, provider, name)
);

create table public.contact_channel_identities (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid not null,
  provider public.provider_code not null,
  external_id text not null,
  status text not null default 'unverified' check (status in ('unverified', 'verified', 'invalid')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  unique (organization_id, id),
  unique (organization_id, provider, external_id)
);

create table public.organization_member_channel_identities (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  member_id uuid not null,
  provider public.provider_code not null,
  feishu_open_id text,
  feishu_user_id text,
  external_id text,
  status text not null default 'unverified' check (status in ('unverified', 'verified', 'invalid')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, member_id) references public.organization_members(organization_id, id) on delete restrict,
  unique (organization_id, id),
  unique (organization_id, provider, member_id),
  check (provider <> 'feishu_internal' or feishu_open_id is not null)
);

create table public.message_drafts (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid not null,
  lead_id uuid,
  opportunity_id uuid,
  owner_member_id uuid,
  created_by_member_id uuid,
  approved_by_member_id uuid,
  provider public.provider_code not null default 'manual',
  status public.message_draft_status not null default 'draft',
  content text not null check (length(btrim(content)) > 0),
  ai_provider text,
  ai_model text,
  prompt_version text,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  approved_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, opportunity_id) references public.opportunities(organization_id, id) on delete restrict,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, created_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, approved_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id)
);

create table public.messages (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  contact_id uuid not null,
  lead_id uuid,
  opportunity_id uuid,
  message_draft_id uuid,
  owner_member_id uuid,
  sent_by_member_id uuid,
  provider public.provider_code not null,
  actual_channel public.manual_channel,
  direction public.message_direction not null,
  status public.message_status not null default 'recorded',
  content text not null check (length(btrim(content)) > 0),
  external_message_id text,
  outcome public.message_outcome,
  notes text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, contact_id) references public.contacts(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, opportunity_id) references public.opportunities(organization_id, id) on delete restrict,
  foreign key (organization_id, message_draft_id) references public.message_drafts(organization_id, id) on delete set null,
  foreign key (organization_id, owner_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, sent_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  check (provider <> 'manual' or actual_channel is not null),
  check (status <> 'sent' or sent_at is not null)
);

create table public.delivery_events (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  message_id uuid,
  provider public.provider_code not null,
  source_event_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, message_id) references public.messages(organization_id, id) on delete restrict,
  unique (organization_id, id),
  unique (organization_id, provider, source_event_id)
);
