create table public.organization_assignment_settings (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  strategy public.assignment_strategy not null default 'round_robin',
  auto_assignment_enabled boolean not null default true,
  daily_limit_enabled boolean not null default false,
  default_daily_limit integer check (default_daily_limit is null or default_daily_limit >= 0),
  first_response_sla_minutes integer not null default 60 check (first_response_sla_minutes between 5 and 10080),
  fallback_strategy public.assignment_strategy not null default 'manager_manual',
  lead_deduplication_window_days integer not null default 30 check (lead_deduplication_window_days between 1 and 365),
  draft_approval_required boolean not null default false,
  sales_self_approval_enabled boolean not null default true,
  rule_version integer not null default 1 check (rule_version > 0),
  updated_by_member_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, updated_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id),
  unique (organization_id, id),
  check (fallback_strategy = 'manager_manual')
);

create table public.assignment_history (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  lead_id uuid not null,
  from_member_id uuid,
  to_member_id uuid,
  reason public.assignment_reason not null,
  reason_notes text,
  assigned_by_member_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  foreign key (organization_id, from_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, to_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, assigned_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id)
);

create table public.lead_source_connections (
  id uuid primary key default extensions.gen_random_uuid(),
  public_id text not null default encode(extensions.gen_random_bytes(18), 'hex'),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  provider text not null check (provider in ('tally', 'generic_webhook', 'internal_manual', 'builtin_form')),
  name text not null,
  status public.connection_status not null default 'draft',
  external_source_id text,
  secret_ref text,
  mapping jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  rate_limit_per_minute integer not null default 60 check (rate_limit_per_minute between 1 and 10000),
  max_payload_bytes integer not null default 262144 check (max_payload_bytes between 1024 and 1048576),
  created_by_member_id uuid,
  validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, created_by_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (public_id),
  unique (organization_id, id),
  unique (organization_id, provider, external_source_id)
);

create table public.inbound_events (
  id uuid primary key default extensions.gen_random_uuid(),
  request_id uuid not null default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  source_connection_id uuid not null,
  provider text not null,
  source_event_id text not null,
  schema_version text not null default '1.0',
  status public.inbound_event_status not null default 'accepted',
  raw_payload jsonb not null,
  normalized_payload jsonb not null,
  payload_sha256 text not null,
  lead_id uuid,
  received_at timestamptz not null,
  processed_at timestamptz,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, source_connection_id) references public.lead_source_connections(organization_id, id) on delete restrict,
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete restrict,
  unique (organization_id, id),
  unique (organization_id, provider, source_event_id)
);

create table public.command_executions (
  id uuid primary key default extensions.gen_random_uuid(),
  command_id uuid not null,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  idempotency_key text not null,
  command_name text not null,
  actor_user_id uuid not null,
  actor_member_id uuid,
  target_type text not null,
  target_id uuid,
  expected_version bigint,
  source text not null check (source in ('crm', 'feishu', 'n8n', 'system')),
  occurred_at timestamptz not null,
  request_hash text not null,
  request_payload jsonb not null,
  status public.command_status not null default 'processing',
  response jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  foreign key (organization_id, actor_member_id) references public.organization_members(organization_id, id) on delete set null,
  unique (organization_id, id),
  unique (organization_id, idempotency_key),
  unique (command_id)
);

create table public.outbox_events (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  aggregate_type text not null,
  aggregate_id uuid,
  event_type text not null,
  deduplication_key text,
  payload jsonb not null default '{}'::jsonb,
  status public.outbox_status not null default 'pending',
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 10 check (max_attempts between 1 and 100),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  completed_at timestamptz,
  last_error_code text,
  last_error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  unique (organization_id, id)
);

create table public.automation_runs (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  workflow_key text not null,
  external_execution_id text,
  outbox_event_id uuid,
  status public.automation_run_status not null default 'running',
  attempt integer not null default 1 check (attempt > 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_code text,
  error_message text,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, outbox_event_id) references public.outbox_events(organization_id, id) on delete set null,
  unique (organization_id, id),
  unique (organization_id, workflow_key, external_execution_id)
);

create table public.audit_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  actor_user_id uuid,
  actor_member_id uuid,
  action text not null,
  target_type text not null,
  target_id uuid,
  source text not null,
  command_execution_id uuid,
  before_state jsonb,
  after_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, actor_member_id) references public.organization_members(organization_id, id) on delete set null,
  foreign key (organization_id, command_execution_id) references public.command_executions(organization_id, id) on delete set null,
  unique (organization_id, id)
);

create table public.organization_purge_jobs (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  status public.purge_job_status not null default 'scheduled',
  current_phase text not null default 'storage',
  cursor jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  scheduled_at timestamptz not null,
  started_at timestamptz,
  completed_at timestamptz,
  last_error_code text,
  last_error_message text,
  purge_report jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version bigint not null default 1 check (version > 0),
  unique (organization_id, id)
);

create table public.organization_tombstones (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id_hash text not null,
  organization_name_hash text not null,
  requested_at timestamptz not null,
  purged_at timestamptz not null,
  status text not null check (status = 'deleted'),
  audit_reference_hash text not null,
  purge_report_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id_hash)
);
